/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PagerDuty.ApiClient.Api;
using PagerDuty.ApiClient.Model;
using PagerDuty.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PagerDuty.ApiClient.Test
{
    /// <summary>
    ///  Class for testing NotificationSubscriptionWithContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationSubscriptionWithContextTests
    {
        // TODO uncomment below to declare an instance variable for NotificationSubscriptionWithContext
        //private NotificationSubscriptionWithContext instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationSubscriptionWithContext
            //instance = new NotificationSubscriptionWithContext();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationSubscriptionWithContext
        /// </summary>
        [Test]
        public void NotificationSubscriptionWithContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificationSubscriptionWithContext
            //Assert.IsInstanceOfType<NotificationSubscriptionWithContext> (instance, "variable 'instance' is a NotificationSubscriptionWithContext");
        }


        /// <summary>
        /// Test the property 'SubscriberId'
        /// </summary>
        [Test]
        public void SubscriberIdTest()
        {
            // TODO unit test for the property 'SubscriberId'
        }
        /// <summary>
        /// Test the property 'SubscriberType'
        /// </summary>
        [Test]
        public void SubscriberTypeTest()
        {
            // TODO unit test for the property 'SubscriberType'
        }
        /// <summary>
        /// Test the property 'SubscribableId'
        /// </summary>
        [Test]
        public void SubscribableIdTest()
        {
            // TODO unit test for the property 'SubscribableId'
        }
        /// <summary>
        /// Test the property 'SubscribableType'
        /// </summary>
        [Test]
        public void SubscribableTypeTest()
        {
            // TODO unit test for the property 'SubscribableType'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
