/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PagerDuty.ApiClient.Api;
using PagerDuty.ApiClient.Model;
using PagerDuty.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PagerDuty.ApiClient.Test
{
    /// <summary>
    ///  Class for testing Schedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduleTests
    {
        // TODO uncomment below to declare an instance variable for Schedule
        //private Schedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Schedule
            //instance = new Schedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Schedule
        /// </summary>
        [Test]
        public void ScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Schedule
            //Assert.IsInstanceOfType<Schedule> (instance, "variable 'instance' is a Schedule");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ScheduleLayers'
        /// </summary>
        [Test]
        public void ScheduleLayersTest()
        {
            // TODO unit test for the property 'ScheduleLayers'
        }
        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Test]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FinalSchedule'
        /// </summary>
        [Test]
        public void FinalScheduleTest()
        {
            // TODO unit test for the property 'FinalSchedule'
        }
        /// <summary>
        /// Test the property 'OverridesSubschedule'
        /// </summary>
        [Test]
        public void OverridesSubscheduleTest()
        {
            // TODO unit test for the property 'OverridesSubschedule'
        }
        /// <summary>
        /// Test the property 'EscalationPolicies'
        /// </summary>
        [Test]
        public void EscalationPoliciesTest()
        {
            // TODO unit test for the property 'EscalationPolicies'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Test]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
        /// <summary>
        /// Test the property 'Teams'
        /// </summary>
        [Test]
        public void TeamsTest()
        {
            // TODO unit test for the property 'Teams'
        }

    }

}
