/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using PagerDuty.ApiClient.Client;
using PagerDuty.ApiClient.Api;

namespace PagerDuty.ApiClient.Test
{
    /// <summary>
    ///  Class for testing StatusDashboardsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StatusDashboardsApiTests
    {
        private StatusDashboardsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StatusDashboardsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusDashboardsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StatusDashboardsApi
            //Assert.IsInstanceOfType(typeof(StatusDashboardsApi), instance, "instance is a StatusDashboardsApi");
        }

        /// <summary>
        /// Test GetStatusDashboardById
        /// </summary>
        [Test]
        public void GetStatusDashboardByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string id = null;
            //string X_EARLY_ACCESS = null;
            //var response = instance.GetStatusDashboardById(accept, id, X_EARLY_ACCESS);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetStatusDashboardByUrlSlug
        /// </summary>
        [Test]
        public void GetStatusDashboardByUrlSlugTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string urlSlug = null;
            //string X_EARLY_ACCESS = null;
            //var response = instance.GetStatusDashboardByUrlSlug(accept, urlSlug, X_EARLY_ACCESS);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetStatusDashboardServiceImpactsById
        /// </summary>
        [Test]
        public void GetStatusDashboardServiceImpactsByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string id = null;
            //string X_EARLY_ACCESS = null;
            //string additionalFields = null;
            //var response = instance.GetStatusDashboardServiceImpactsById(accept, id, X_EARLY_ACCESS, additionalFields);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetStatusDashboardServiceImpactsByUrlSlug
        /// </summary>
        [Test]
        public void GetStatusDashboardServiceImpactsByUrlSlugTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string urlSlug = null;
            //string X_EARLY_ACCESS = null;
            //string additionalFields = null;
            //var response = instance.GetStatusDashboardServiceImpactsByUrlSlug(accept, urlSlug, X_EARLY_ACCESS, additionalFields);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ListStatusDashboards
        /// </summary>
        [Test]
        public void ListStatusDashboardsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //string X_EARLY_ACCESS = null;
            //var response = instance.ListStatusDashboards(accept, X_EARLY_ACCESS);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
