/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PagerDuty.ApiClient.Client.SwaggerDateConverter;

namespace PagerDuty.ApiClient.Model
{
    /// <summary>
    /// EditableTemplate
    /// </summary>
    [DataContract]
        public partial class EditableTemplate :  IEquatable<EditableTemplate>, IValidatableObject
    {
        /// <summary>
        /// The type of template (&#x60;status_update&#x60; is the only supported template at this time)
        /// </summary>
        /// <value>The type of template (&#x60;status_update&#x60; is the only supported template at this time)</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TemplateTypeEnum
        {
            /// <summary>
            /// Enum Statusupdate for value: status_update
            /// </summary>
            [EnumMember(Value = "status_update")]
            Statusupdate = 1        }
        /// <summary>
        /// The type of template (&#x60;status_update&#x60; is the only supported template at this time)
        /// </summary>
        /// <value>The type of template (&#x60;status_update&#x60; is the only supported template at this time)</value>
        [DataMember(Name="template_type", EmitDefaultValue=false)]
        public TemplateTypeEnum? TemplateType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EditableTemplate" /> class.
        /// </summary>
        /// <param name="templateType">The type of template (&#x60;status_update&#x60; is the only supported template at this time).</param>
        /// <param name="name">The name of the template.</param>
        /// <param name="description">Description of the template.</param>
        /// <param name="templatedFields">templatedFields.</param>
        public EditableTemplate(TemplateTypeEnum? templateType = default(TemplateTypeEnum?), string name = default(string), string description = default(string), Object templatedFields = default(Object))
        {
            this.TemplateType = templateType;
            this.Name = name;
            this.Description = description;
            this.TemplatedFields = templatedFields;
        }
        

        /// <summary>
        /// The name of the template
        /// </summary>
        /// <value>The name of the template</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the template
        /// </summary>
        /// <value>Description of the template</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets TemplatedFields
        /// </summary>
        [DataMember(Name="templated_fields", EmitDefaultValue=false)]
        public Object TemplatedFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EditableTemplate {\n");
            sb.Append("  TemplateType: ").Append(TemplateType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TemplatedFields: ").Append(TemplatedFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EditableTemplate);
        }

        /// <summary>
        /// Returns true if EditableTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of EditableTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EditableTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TemplateType == input.TemplateType ||
                    (this.TemplateType != null &&
                    this.TemplateType.Equals(input.TemplateType))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.TemplatedFields == input.TemplatedFields ||
                    (this.TemplatedFields != null &&
                    this.TemplatedFields.Equals(input.TemplatedFields))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TemplateType != null)
                    hashCode = hashCode * 59 + this.TemplateType.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.TemplatedFields != null)
                    hashCode = hashCode * 59 + this.TemplatedFields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
