/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PagerDuty.ApiClient.Client.SwaggerDateConverter;

namespace PagerDuty.ApiClient.Model
{
    /// <summary>
    /// ScheduledAction
    /// </summary>
    [DataContract]
        public partial class ScheduledAction :  IEquatable<ScheduledAction>, IValidatableObject
    {
        /// <summary>
        /// The type of schedule action. Must be set to urgency_change.
        /// </summary>
        /// <value>The type of schedule action. Must be set to urgency_change.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Urgencychange for value: urgency_change
            /// </summary>
            [EnumMember(Value = "urgency_change")]
            Urgencychange = 1        }
        /// <summary>
        /// The type of schedule action. Must be set to urgency_change.
        /// </summary>
        /// <value>The type of schedule action. Must be set to urgency_change.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Urgency level. Must be set to high.
        /// </summary>
        /// <value>Urgency level. Must be set to high.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ToUrgencyEnum
        {
            /// <summary>
            /// Enum High for value: high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 1        }
        /// <summary>
        /// Urgency level. Must be set to high.
        /// </summary>
        /// <value>Urgency level. Must be set to high.</value>
        [DataMember(Name="to_urgency", EmitDefaultValue=false)]
        public ToUrgencyEnum ToUrgency { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledAction" /> class.
        /// </summary>
        /// <param name="type">The type of schedule action. Must be set to urgency_change. (required).</param>
        /// <param name="at">Represents when scheduled action will occur. (required).</param>
        /// <param name="toUrgency">Urgency level. Must be set to high. (required).</param>
        public ScheduledAction(TypeEnum type = default(TypeEnum), Object at = default(Object), ToUrgencyEnum toUrgency = default(ToUrgencyEnum))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for ScheduledAction and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "at" is required (not null)
            if (at == null)
            {
                throw new InvalidDataException("at is a required property for ScheduledAction and cannot be null");
            }
            else
            {
                this.At = at;
            }
            // to ensure "toUrgency" is required (not null)
            if (toUrgency == null)
            {
                throw new InvalidDataException("toUrgency is a required property for ScheduledAction and cannot be null");
            }
            else
            {
                this.ToUrgency = toUrgency;
            }
        }
        

        /// <summary>
        /// Represents when scheduled action will occur.
        /// </summary>
        /// <value>Represents when scheduled action will occur.</value>
        [DataMember(Name="at", EmitDefaultValue=false)]
        public Object At { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduledAction {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  At: ").Append(At).Append("\n");
            sb.Append("  ToUrgency: ").Append(ToUrgency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduledAction);
        }

        /// <summary>
        /// Returns true if ScheduledAction instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduledAction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledAction input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.At == input.At ||
                    (this.At != null &&
                    this.At.Equals(input.At))
                ) && 
                (
                    this.ToUrgency == input.ToUrgency ||
                    (this.ToUrgency != null &&
                    this.ToUrgency.Equals(input.ToUrgency))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.At != null)
                    hashCode = hashCode * 59 + this.At.GetHashCode();
                if (this.ToUrgency != null)
                    hashCode = hashCode * 59 + this.ToUrgency.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
